wandb_version: 1

BATCH_NUM:
  desc: null
  value: 40
DIM:
  desc: null
  value: 128
DROPOUT:
  desc: null
  value: 0.35
EPOCH_NUM:
  desc: null
  value: 50
INPUT:
  desc: null
  value: ..\input\rfcx-species-audio-detection\train
KERNEL_SIZE:
  desc: null
  value: 3
NUM_BIRDS:
  desc: null
  value: 24
N_FOLDS:
  desc: null
  value: 5
POOL_SIZE:
  desc: null
  value: 2
POOL_STRIDE:
  desc: null
  value: 2
SEED:
  desc: null
  value: 42
SEQ_LEN:
  desc: null
  value: 2813
SUB:
  desc: null
  value: ..\input\rfcx-species-audio-detection\sample_submission.csv
TEST_AUDIO_ROOT:
  desc: null
  value: ..\input\rfcx-species-audio-detection\test_mel
TRAIN_AUDIO_ROOT:
  desc: null
  value: ..\input\rfcx-species-audio-detection\train_mel
TRAIN_TP:
  desc: null
  value: ..\input\rfcx-species-audio-detection\train_tp.csv
VALID_BATCH_NUM:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.15
      8:
      - 1
      - 3
eta_min:
  desc: null
  value: 1.0e-05
lr:
  desc: null
  value: 0.0001
t_max:
  desc: null
  value: 10
